name: farahs_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  external_app_launcher: ^4.0.0
  url_launcher: ^6.3.0
  hive: any
  hive_flutter: any
  permission_handler: ^12.0.0+1
  flutter_localization: ^0.3.2
  get: ^4.6.6
  get_storage: ^2.1.1
  audioplayers: ^6.1.0
  font_awesome_flutter: ^10.8.0
  flutter_animate: ^4.5.2
  http: ^1.2.2
  path_provider: ^2.0.15
  fluttertoast: ^8.2.8
  awesome_notifications: ^0.10.0
  intl: ^0.20.2  # Updated from ^0.19.0 to ^0.20.2
  table_calendar: ^3.1.2
  path: ^1.9.0
  bottom_navy_bar: ^6.1.0
  animate_do: ^4.2.0
  just_audio: ^0.10.3
  flutter_slidable: ^4.0.0
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.1.0
  sqflite: ^2.4.1
  flutter_staggered_grid_view: ^0.7.0
  health: ^12.2.0
  fl_chart: ^1.0.0
dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/next to you.mp3
    - assets/birthday.mp3
    - assets/Screenshot (4).jpg

  fonts:
    - family: Teko
      fonts:
        - asset: assets/teko-regular.ttf
