import 'lessons_model.dart';
class LessonRepository {
  final List<LessonModel> _lessons = [
    LessonModel(
      englishWord: "Serendipity",
      arabicTranslation: "الصدفة السعيدة",
      phrase: "Her discovery was a serendipity.",
      explanation: "Finding something good without looking for it.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Euphoria",
      arabicTranslation: "الفرح الغامر",
      phrase: "He was filled with euphoria after winning.",
      explanation: "A feeling of intense happiness or excitement.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Ephemeral",
      arabicTranslation: "الزوال السريع",
      phrase: "The beauty of the sunset was ephemeral.",
      explanation: "Lasting for a very short time.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Ineffable",
      arabicTranslation: "لا يوصف",
      phrase: "The view from the mountaintop was ineffable.",
      explanation: "Too great to be expressed in words.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Petrichor",
      arabicTranslation: "رائحة المطر",
      phrase: "The petrichor after the rain was soothing.",
      explanation: "The pleasant smell of rain after a dry spell.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Limerence",
      arabicTranslation: "الهيام",
      phrase: "She felt a sense of limerence for him.",
      explanation: "The state of being infatuated or obsessed with someone.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Quintessential",
      arabicTranslation: "جوهري",
      phrase: "This dish is the quintessential Italian meal.",
      explanation: "Representing the most perfect or typical example of something.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Mellifluous",
      arabicTranslation: "عذب",
      phrase: "Her mellifluous voice captivated the audience.",
      explanation: "Sweet and smooth; pleasant to hear.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Halcyon",
      arabicTranslation: "هادئ",
      phrase: "The halcyon days of summer are my favorite.",
      explanation: "Calm, peaceful, and prosperous.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Effervescent",
      arabicTranslation: "مفعم بالحيوية",
      phrase: "Her effervescent personality made everyone smile.",
      explanation: "Bubbling with energy and enthusiasm.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Zenith",
      arabicTranslation: "ذروة",
      phrase: "The company reached its zenith in the early 2000s.",
      explanation: "The highest point or peak.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Solitude",
      arabicTranslation: "العزلة",
      phrase: "He enjoyed the solitude of the mountains.",
      explanation: "The state of being alone without feeling lonely.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Resilience",
      arabicTranslation: "المرونة",
      phrase: "Her resilience in tough times was admirable.",
      explanation: "The ability to recover quickly from difficulties.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Ambivalence",
      arabicTranslation: "التردد",
      phrase: "She felt ambivalence about moving to a new city.",
      explanation: "Having mixed feelings or contradictory ideas about something.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Plethora",
      arabicTranslation: "وفرة",
      phrase: "There was a plethora of options at the buffet.",
      explanation: "An excess or abundance of something.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Nostalgia",
      arabicTranslation: "الحنين إلى الماضي",
      phrase: "Hearing the song filled her with nostalgia.",
      explanation: "A sentimental longing for the past.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Ambience",
      arabicTranslation: "الجو العام",
      phrase: "The restaurant's ambience was perfect for a romantic dinner.",
      explanation: "The character and atmosphere of a place.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Eloquent",
      arabicTranslation: "بليغ",
      phrase: "Her speech was so eloquent that it moved the audience.",
      explanation: "Fluent or persuasive in speaking or writing.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Serene",
      arabicTranslation: "هادئ",
      phrase: "The lake was serene and calm at dawn.",
      explanation: "Calm, peaceful, and untroubled.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Epiphany",
      arabicTranslation: "لحظة الإدراك",
      phrase: "She had an epiphany about her life's purpose.",
      explanation: "A sudden realization or insight.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Ebullient",
      arabicTranslation: "مبتهج",
      phrase: "His ebullient mood was contagious.",
      explanation: "Full of energy and enthusiasm.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Iridescent",
      arabicTranslation: "متلألئ",
      phrase: "The soap bubble was iridescent in the sunlight.",
      explanation: "Showing luminous colors that seem to change when seen from different angles.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Cacophony",
      arabicTranslation: "صخب",
      phrase: "The cacophony of horns made it hard to concentrate.",
      explanation: "A harsh, discordant mixture of sounds.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Effulgent",
      arabicTranslation: "مشرق",
      phrase: "Her effulgent smile lit up the room.",
      explanation: "Radiant, shining brightly.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Aesthetic",
      arabicTranslation: "جمالي",
      phrase: "The painting's aesthetic value was undeniable.",
      explanation: "Concerned with beauty or the appreciation of beauty.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Oblivion",
      arabicTranslation: "نسيان",
      phrase: "He drank himself into oblivion.",
      explanation: "The state of being unaware or unconscious.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Labyrinth",
      arabicTranslation: "متاهة",
      phrase: "The city's narrow streets were a labyrinth.",
      explanation: "A complex and confusing network of paths or passages.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Incandescent",
      arabicTranslation: "متوهج",
      phrase: "The room was lit by an incandescent bulb.",
      explanation: "Emitting light as a result of being heated.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Panacea",
      arabicTranslation: "دواء لكل داء",
      phrase: "There's no panacea for all life's problems.",
      explanation: "A solution or remedy for all difficulties or diseases.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Benevolent",
      arabicTranslation: "خيّر",
      phrase: "The benevolent man donated generously to the charity.",
      explanation: "Well-meaning and kindly.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Inequity",
      arabicTranslation: "ظلم",
      phrase: "The system was plagued by inequity.",
      explanation: "Lack of fairness or justice.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "G'day",
      arabicTranslation: "مرحباً",
      phrase: "Australians often say 'G'day mate' to greet one another.",
      explanation: "A casual way of saying 'hello' in Australia.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Aussie",
      arabicTranslation: "أسترالي",
      phrase: "The Aussies are known for their friendly nature.",
      explanation: "A colloquial term for Australians.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Mate",
      arabicTranslation: "صديق",
      phrase: "'Cheers, mate' is commonly used to say 'thanks'.",
      explanation: "An informal term for a friend.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Outback",
      arabicTranslation: "البرية",
      phrase: "The Outback is a must-see for adventurers visiting Australia.",
      explanation: "The remote and arid interior of Australia.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Vegemite",
      arabicTranslation: "فيجيمايت",
      phrase: "Many Australians enjoy Vegemite on toast for breakfast.",
      explanation: "A popular spread made from yeast extract.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Koala",
      arabicTranslation: "الكوالا",
      phrase: "Koalas are often seen resting in eucalyptus trees.",
      explanation: "A marsupial native to Australia.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Barbie",
      arabicTranslation: "شواء",
      phrase: "Australians love having a barbie by the beach.",
      explanation: "Slang for a barbecue.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Boomerang",
      arabicTranslation: "البوميرانج",
      phrase: "Boomerangs were traditionally used by Aboriginal Australians.",
      explanation: "A curved tool that returns when thrown correctly.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Billabong",
      arabicTranslation: "بركة ماء",
      phrase: "We stopped by a billabong during our hike.",
      explanation: "A stagnant water body in a river.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "No worries",
      arabicTranslation: "لا تقلق",
      phrase: "If you thank someone, they might reply with 'No worries'.",
      explanation: "A common way of saying 'It's okay' or 'You're welcome'.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Kangaroo",
      arabicTranslation: "الكنغر",
      phrase: "Kangaroos are a common sight in Australia's rural areas.",
      explanation: "A marsupial known for its strong legs and hopping.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Fair dinkum",
      arabicTranslation: "حقاً",
      phrase: "Are you fair dinkum about traveling to the Outback?",
      explanation: "An Australian phrase meaning 'genuine' or 'true'.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Avocado smash",
      arabicTranslation: "هرس الأفوكادو",
      phrase: "Avocado smash is a popular dish in Australian cafes.",
      explanation: "A breakfast dish made with smashed avocado on toast.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Sunnies",
      arabicTranslation: "نظارات شمسية",
      phrase: "Don't forget your sunnies before heading to the beach.",
      explanation: "Slang for sunglasses.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Arvo",
      arabicTranslation: "عصر",
      phrase: "Let's meet in the arvo for coffee.",
      explanation: "Australian slang for 'afternoon'.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Bogan",
      arabicTranslation: "غير مهذب",
      phrase: "That outfit makes you look like a bogan!",
      explanation: "A slang term for an unsophisticated person.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Thongs",
      arabicTranslation: "شبشب",
      phrase: "Australians call flip-flops 'thongs'.",
      explanation: "Slang for a type of footwear.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Servo",
      arabicTranslation: "محطة وقود",
      phrase: "Stop at the servo to fill up the car.",
      explanation: "Australian slang for a service station or gas station.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Esky",
      arabicTranslation: "صندوق تبريد",
      phrase: "We packed the drinks in the esky for the picnic.",
      explanation: "A portable cooler for keeping food and drinks cold.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Roo",
      arabicTranslation: "كنغر",
      phrase: "We spotted a roo while driving through the bush.",
      explanation: "Slang for a kangaroo.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Bush",
      arabicTranslation: "البرية",
      phrase: "The family went camping in the bush over the weekend.",
      explanation: "A term for wilderness or rural areas in Australia.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Cuppa",
      arabicTranslation: "فنجان شاي",
      phrase: "Would you like a cuppa tea or coffee?",
      explanation: "Slang for a cup of tea.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Stubby",
      arabicTranslation: "زجاجة بيرة",
      phrase: "He grabbed a stubby from the fridge.",
      explanation: "Slang for a small bottle of beer.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Swag",
      arabicTranslation: "معدات التخييم",
      phrase: "We carried our swag for camping in the Outback.",
      explanation: "A portable sleeping setup for camping.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Brekkie",
      arabicTranslation: "وجبة الإفطار",
      phrase: "Let's grab some brekkie before heading out.",
      explanation: "Australian slang for breakfast.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Chook",
      arabicTranslation: "دجاجة",
      phrase: "They have a pet chook in their backyard.",
      explanation: "Slang for a chicken.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Macca's",
      arabicTranslation: "ماكدونالدز",
      phrase: "Let's stop at Macca's for some burgers.",
      explanation: "Slang for McDonald's in Australia.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Platypus",
      arabicTranslation: "خلد الماء",
      phrase: "The platypus is one of Australia's unique animals.",
      explanation: "An unusual egg-laying mammal found in Australia.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Wombat",
      arabicTranslation: "الومبت",
      phrase: "We saw a wombat crossing the road at dusk.",
      explanation: "A small, burrowing marsupial native to Australia.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Crocs",
      arabicTranslation: "تماسيح",
      phrase: "Be cautious of crocs in the northern rivers.",
      explanation: "Slang for crocodiles, common in northern Australia.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Brolly",
      arabicTranslation: "مظلة",
      phrase: "Don't forget your brolly; it might rain later.",
      explanation: "Australian slang for umbrella.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Footy",
      arabicTranslation: "كرة القدم الأسترالية",
      phrase: "Australians love watching footy on the weekends.",
      explanation: "Slang for Australian Rules Football or Rugby.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Snag",
      arabicTranslation: "نقانق",
      phrase: "We cooked snags on the barbecue for dinner.",
      explanation: "Australian slang for sausages.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Sheila",
      arabicTranslation: "فتاة",
      phrase: "That sheila at the café was very friendly.",
      explanation: "An informal term for a woman.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Bloke",
      arabicTranslation: "رجل",
      phrase: "The bloke at the counter was very helpful.",
      explanation: "An informal term for a man.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Crikey",
      arabicTranslation: "يا للهول",
      phrase: "Crikey, that's a massive spider!",
      explanation: "An exclamation of surprise or amazement.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Echidna",
      arabicTranslation: "آكل النمل الشوكي",
      phrase: "The echidna is another egg-laying mammal from Australia.",
      explanation: "A spiny anteater native to Australia.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Choccy",
      arabicTranslation: "شيكولاتة",
      phrase: "Would you like a choccy biscuit with your tea?",
      explanation: "Slang for chocolate.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Mozzie",
      arabicTranslation: "بعوضة",
      phrase: "Be sure to use insect repellent to avoid mozzies.",
      explanation: "Slang for mosquitoes.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Ripper",
      arabicTranslation: "رائع",
      phrase: "That was a ripper of a game last night!",
      explanation: "An expression meaning something is fantastic or excellent.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Larrikin",
      arabicTranslation: "شخص مرح",
      phrase: "He's a real larrikin, always making people laugh.",
      explanation: "A term for someone who is playful or mischievous.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Ute",
      arabicTranslation: "شاحنة صغيرة",
      phrase: "They loaded the tools onto the ute for the trip.",
      explanation: "Slang for a utility vehicle or pickup truck.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Bikkie",
      arabicTranslation: "بسكويت",
      phrase: "Tea with a bikkie is an Australian classic.",
      explanation: "Slang for a biscuit or cookie.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Fair go",
      arabicTranslation: "فرصة عادلة",
      phrase: "All anyone asks for is a fair go.",
      explanation: "A phrase advocating fairness or equal opportunity.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Crocodile Dundee",
      arabicTranslation: "تمساح دندي",
      phrase: "The movie 'Crocodile Dundee' made the Outback famous.",
      explanation: "A famous Australian movie character symbolizing adventure.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Bush tucker",
      arabicTranslation: "طعام البرية",
      phrase: "The guide showed us examples of bush tucker.",
      explanation: "Native Australian foods traditionally eaten by Indigenous Australians.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Ta",
      arabicTranslation: "شكراً",
      phrase: "Ta for your help with the directions.",
      explanation: "A casual way of saying 'thank you'.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Jumper",
      arabicTranslation: "سترة",
      phrase: "It gets cold in the evenings, so bring a jumper.",
      explanation: "Australian term for a sweater or pullover.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Walkabout",
      arabicTranslation: "تجول",
      phrase: "The guide explained the concept of a walkabout.",
      explanation: "A journey into the bush, often for spiritual reasons.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Bottle-o",
      arabicTranslation: "متجر لبيع الكحول",
      phrase: "Let's stop by the bottle-o to get some drinks.",
      explanation: "Slang for a liquor store.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Pavlova",
      arabicTranslation: "حلويات بافلوفا",
      phrase: "Pavlova is a popular dessert at Australian celebrations.",
      explanation: "A meringue-based dessert topped with fruit and cream.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Straya",
      arabicTranslation: "أستراليا",
      phrase: "Many Aussies lovingly refer to their country as Straya.",
      explanation: "Slang for Australia, emphasizing its pronunciation.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Capsicum",
      arabicTranslation: "فلفل حلو",
      phrase: "Add some capsicum to the salad for color.",
      explanation: "Australian term for bell peppers.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Cairns",
      arabicTranslation: "كيرنز",
      phrase: "Cairns is the gateway to the Great Barrier Reef.",
      explanation: "A tropical city in Queensland, Australia.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Tassie",
      arabicTranslation: "تاسمانيا",
      phrase: "Tassie has some of the most beautiful landscapes in Australia.",
      explanation: "Slang for Tasmania, an island state of Australia.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Semester",
      arabicTranslation: "فصل دراسي",
      phrase: "The semester starts in March and ends in June.",
      explanation: "A half-year term in a school or university.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Lecture",
      arabicTranslation: "محاضرة",
      phrase: "I have a lecture on biology at 10:00 AM.",
      explanation: "An educational talk given to a group of students.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Tutorial",
      arabicTranslation: "درس خصوصي",
      phrase: "The tutorial session helps clarify the lecture material.",
      explanation: "A small class for discussion and detailed teaching.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Assignment",
      arabicTranslation: "واجب دراسي",
      phrase: "We need to submit our assignment by Friday.",
      explanation: "A task or piece of work assigned to students.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Campus",
      arabicTranslation: "الحرم الجامعي",
      phrase: "The library is located at the center of the campus.",
      explanation: "The grounds and buildings of a university or college.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Canteen",
      arabicTranslation: "كافتيريا",
      phrase: "We grabbed lunch from the canteen between lectures.",
      explanation: "A cafeteria at a school or university.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Enrolment",
      arabicTranslation: "التسجيل",
      phrase: "Enrolment for the new semester closes next week.",
      explanation: "The process of registering for classes or a course.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Elective",
      arabicTranslation: "مادة اختيارية",
      phrase: "I chose photography as my elective this semester.",
      explanation: "A course that students choose, not mandatory.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Credit Points",
      arabicTranslation: "نقاط الاعتماد",
      phrase: "You need 24 credit points to complete the degree.",
      explanation: "Units used to measure academic progress.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Orientation",
      arabicTranslation: "التوجيه",
      phrase: "Orientation week helps new students settle into university life.",
      explanation: "A program to familiarize new students with campus life.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Practical",
      arabicTranslation: "عملي",
      phrase: "The practical session is held in the science lab.",
      explanation: "A hands-on activity or experiment in a subject.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Study Load",
      arabicTranslation: "عبء الدراسة",
      phrase: "Managing your study load is key to academic success.",
      explanation: "The number of courses or units taken in a semester.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Placement",
      arabicTranslation: "التدريب العملي",
      phrase: "My placement in a local clinic starts next month.",
      explanation: "Work experience required as part of a course.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Graduate",
      arabicTranslation: "خريج",
      phrase: "He graduated with a degree in engineering last year.",
      explanation: "A person who has completed a course of study.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Thesis",
      arabicTranslation: "رسالة علمية",
      phrase: "She is working on her master's thesis about renewable energy.",
      explanation: "A long essay or dissertation based on research.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Counselor",
      arabicTranslation: "مرشد",
      phrase: "The counselor can help you with academic advice.",
      explanation: "A professional who provides guidance on personal or academic issues.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Scholarship",
      arabicTranslation: "منحة دراسية",
      phrase: "She received a scholarship to cover her tuition fees.",
      explanation: "A financial award for students to support education.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Dean",
      arabicTranslation: "عميد",
      phrase: "The dean of the faculty will speak at the event.",
      explanation: "The head of a college or university faculty.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Library",
      arabicTranslation: "مكتبة",
      phrase: "The library is a quiet place to study.",
      explanation: "A place where books and resources are available for study.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Lecture Theatre",
      arabicTranslation: "قاعة محاضرات",
      phrase: "The lecture theatre can seat over 200 students.",
      explanation: "A large hall used for teaching students.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Major",
      arabicTranslation: "تخصص",
      phrase: "Her major is computer science.",
      explanation: "The primary field of study in a degree program.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Minor",
      arabicTranslation: "تخصص فرعي",
      phrase: "He is pursuing a minor in environmental science.",
      explanation: "A secondary field of study in a degree program.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Assessment",
      arabicTranslation: "التقييم",
      phrase: "This assessment counts for 40% of the final grade.",
      explanation: "A test or evaluation of a student's progress.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Tutor",
      arabicTranslation: "مدرس مساعد",
      phrase: "The tutor helps students understand complex topics.",
      explanation: "A teacher or instructor for small groups.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Syllabus",
      arabicTranslation: "المنهج الدراسي",
      phrase: "The syllabus outlines the topics we will cover this semester.",
      explanation: "An outline of topics to be studied in a course.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Alumni",
      arabicTranslation: "الخريجين",
      phrase: "The university hosts events for its alumni every year.",
      explanation: "Graduates of a particular school, college, or university.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Dunny",
      arabicTranslation: "مرحاض",
      phrase: "Excuse me, where's the dunny?",
      explanation: "Slang for a toilet.",
      createdAt: DateTime.now(),
    ),

    LessonModel(
      englishWord: "Ameliorate",
      arabicTranslation: "تحسين",
      phrase: "Efforts were made to ameliorate the situation.",
      explanation: "To make something better or improve it.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Elucidate",
      arabicTranslation: "توضيح",
      phrase: "Could you elucidate your point further?",
      explanation: "To make something clear or explain.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Solace",
      arabicTranslation: "عزاء",
      phrase: "She found solace in her family during tough times.",
      explanation: "Comfort in sorrow or trouble.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Fortitude",
      arabicTranslation: "الشجاعة",
      phrase: "He showed great fortitude in the face of adversity.",
      explanation: "Courage in pain or adversity.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Enigma",
      arabicTranslation: "لغز",
      phrase: "The disappearance of the ship remains an enigma.",
      explanation: "A person or thing that is mysterious or difficult to understand.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Veracity",
      arabicTranslation: "صدق",
      phrase: "The veracity of his claims was questioned.",
      explanation: "Conformity to facts; accuracy.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Zephyr",
      arabicTranslation: "نسيم لطيف",
      phrase: "A gentle zephyr cooled the summer air.",
      explanation: "A soft, gentle breeze.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Pristine",
      arabicTranslation: "نقي",
      phrase: "The beach was in pristine condition.",
      explanation: "In its original condition; unspoiled.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Hiraeth",
      arabicTranslation: "الحنين للوطن",
      phrase: "She felt a hiraeth for her childhood home.",
      explanation: "A deep longing for a home you cannot return to.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Ethereal",
      arabicTranslation: "سماوي",
      phrase: "Her ethereal beauty left everyone speechless.",
      explanation: "Extremely delicate and light in a way that seems not of this world.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Reverie",
      arabicTranslation: "شرود",
      phrase: "She was lost in a reverie during the lecture.",
      explanation: "A state of being pleasantly lost in one's thoughts; a daydream.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Grateful",
      arabicTranslation: "ممتن",
      phrase: "She was grateful for her friend's help.",
      explanation: "Feeling or showing thanks.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Delicate",
      arabicTranslation: "رقيق",
      phrase: "The glass is very delicate and can break easily.",
      explanation: "Easily damaged or broken.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Courage",
      arabicTranslation: "شجاعة",
      phrase: "He showed great courage in facing his fears.",
      explanation: "The ability to face danger without fear.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Harmony",
      arabicTranslation: "انسجام",
      phrase: "The colors in the painting create a perfect harmony.",
      explanation: "A pleasing combination of different elements.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Ambition",
      arabicTranslation: "طموح",
      phrase: "Her ambition is to become a doctor.",
      explanation: "A strong desire to achieve something.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Curious",
      arabicTranslation: "فضولي",
      phrase: "He is curious about how airplanes work.",
      explanation: "Eager to learn or know about something.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Precious",
      arabicTranslation: "ثمين",
      phrase: "The necklace is made of precious stones.",
      explanation: "Of great value and not to be wasted.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Unique",
      arabicTranslation: "فريد",
      phrase: "Her talent is unique and unmatched.",
      explanation: "Being the only one of its kind.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Elegant",
      arabicTranslation: "أنيق",
      phrase: "The dress she wore was very elegant.",
      explanation: "Graceful and stylish in appearance or manner.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Optimistic",
      arabicTranslation: "متفائل",
      phrase: "He remains optimistic about his future.",
      explanation: "Expecting good things to happen.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Compassion",
      arabicTranslation: "رحمة",
      phrase: "She felt compassion for the injured animal.",
      explanation: "A feeling of wanting to help someone who is suffering.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Sincere",
      arabicTranslation: "صادق",
      phrase: "His apology was sincere and heartfelt.",
      explanation: "Genuine and without deceit.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Fortunate",
      arabicTranslation: "محظوظ",
      phrase: "They were fortunate to survive the accident.",
      explanation: "Having good luck or good fortune.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Diligent",
      arabicTranslation: "مجتهد",
      phrase: "The diligent student always completes homework on time.",
      explanation: "Showing careful and persistent effort.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Respect",
      arabicTranslation: "احترام",
      phrase: "Children should show respect to their elders.",
      explanation: "A feeling of deep admiration for someone or something.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Generous",
      arabicTranslation: "كريم",
      phrase: "The generous man donated to charity.",
      explanation: "Willing to give more than is necessary or expected.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Patient",
      arabicTranslation: "صبور",
      phrase: "She remained patient while waiting for the bus.",
      explanation: "Able to accept delays or problems calmly.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Genuine",
      arabicTranslation: "حقيقي",
      phrase: "He has a genuine interest in helping others.",
      explanation: "Real, authentic, and sincere.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Flexible",
      arabicTranslation: "مرن",
      phrase: "She is flexible with her schedule.",
      explanation: "Willing to change or adapt.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Confident",
      arabicTranslation: "واثق",
      phrase: "He feels confident about his performance in the exam.",
      explanation: "Having trust in one's abilities.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Loyal",
      arabicTranslation: "وفي",
      phrase: "The dog is loyal to its owner.",
      explanation: "Showing firm and constant support or allegiance.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Gentle",
      arabicTranslation: "لطيف",
      phrase: "He gave the baby a gentle hug.",
      explanation: "Kind and calm; not harsh or severe.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Hopeful",
      arabicTranslation: "مليء بالأمل",
      phrase: "She remains hopeful about the future.",
      explanation: "Feeling or inspiring optimism about a future event.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Creative",
      arabicTranslation: "مبدع",
      phrase: "She is very creative in her artwork.",
      explanation: "Having the ability to create something new or imaginative.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Polite",
      arabicTranslation: "مهذب",
      phrase: "The waiter was polite and helpful.",
      explanation: "Having good manners and showing respect for others.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Cheerful",
      arabicTranslation: "مرح",
      phrase: "His cheerful attitude brightened everyone's day.",
      explanation: "Noticeably happy and optimistic.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Clever",
      arabicTranslation: "ذكي",
      phrase: "The clever student solved the puzzle quickly.",
      explanation: "Quick to understand, learn, and devise ideas.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Faithful",
      arabicTranslation: "مخلص",
      phrase: "He was faithful to his promises.",
      explanation: "Remaining loyal and steadfast.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Peaceful",
      arabicTranslation: "مسالم",
      phrase: "The garden is a peaceful place to relax.",
      explanation: "Free from disturbance or conflict.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Reliable",
      arabicTranslation: "موثوق",
      phrase: "He is a reliable friend you can trust.",
      explanation: "Consistently good in quality or performance.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Friendly",
      arabicTranslation: "ودود",
      phrase: "The new neighbors are very friendly.",
      explanation: "Acting in a kind and pleasant way.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Responsible",
      arabicTranslation: "مسؤول",
      phrase: "She is responsible for completing the project on time.",
      explanation: "Having an obligation to do something or take care of something.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Cautious",
      arabicTranslation: "حذر",
      phrase: "He was cautious while crossing the busy street.",
      explanation: "Taking care to avoid danger or mistakes.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Modest",
      arabicTranslation: "متواضع",
      phrase: "Despite her success, she remains modest.",
      explanation: "Not bragging about one's achievements or qualities.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Forgiving",
      arabicTranslation: "متسامح",
      phrase: "He has a forgiving nature.",
      explanation: "Willing to forgive others for their mistakes.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Enthusiastic",
      arabicTranslation: "متحمس",
      phrase: "She is enthusiastic about starting her new job.",
      explanation: "Showing intense interest and excitement.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Ambitious",
      arabicTranslation: "طموح",
      phrase: "He is an ambitious student aiming for high grades.",
      explanation: "Having a strong desire to achieve success.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Tolerant",
      arabicTranslation: "متسامح",
      phrase: "He is tolerant of different opinions.",
      explanation: "Willing to accept behaviors and beliefs that are different from your own.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Hopeful",
      arabicTranslation: "مليء بالأمل",
      phrase: "She remains hopeful about the future.",
      explanation: "Feeling or inspiring optimism about a future event.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Sensitive",
      arabicTranslation: "حساس",
      phrase: "He is sensitive to criticism.",
      explanation: "Easily affected by feelings or external factors.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Negotiation",
      arabicTranslation: "مفاوضة",
      phrase: "The deal was finalized after a long negotiation.",
      explanation: "A discussion aimed at reaching an agreement.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Proposal",
      arabicTranslation: "اقتراح",
      phrase: "The team submitted a proposal for the new project.",
      explanation: "A plan or suggestion put forward for consideration.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Revenue",
      arabicTranslation: "إيرادات",
      phrase: "The company's revenue increased significantly this year.",
      explanation: "Income generated from business activities.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Expense",
      arabicTranslation: "نفقات",
      phrase: "We need to reduce unnecessary expenses to save money.",
      explanation: "The cost required for something; expenditure.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Client",
      arabicTranslation: "عميل",
      phrase: "Our priority is to keep our clients satisfied.",
      explanation: "A person or organization using the services of another.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Deadline",
      arabicTranslation: "الموعد النهائي",
      phrase: "The report must be submitted before the deadline.",
      explanation: "The latest time or date by which something should be completed.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Partnership",
      arabicTranslation: "شراكة",
      phrase: "They formed a partnership to expand their businesses.",
      explanation: "An association between two or more parties for mutual benefit.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Efficiency",
      arabicTranslation: "كفاءة",
      phrase: "Improving efficiency will reduce costs.",
      explanation: "Achieving maximum productivity with minimum effort or expense.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Aircraft",
      arabicTranslation: "طائرة",
      phrase: "The aircraft landed safely despite the strong winds.",
      explanation: "A machine capable of flight, such as an airplane or helicopter.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Altitude",
      arabicTranslation: "الارتفاع",
      phrase: "The plane reached an altitude of 35,000 feet.",
      explanation: "The height of an object or point in relation to sea level.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Turbulence",
      arabicTranslation: "الاضطرابات الجوية",
      phrase: "The passengers were warned about potential turbulence.",
      explanation: "Irregular or violent movement of air or water.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Runway",
      arabicTranslation: "مدرج الطائرات",
      phrase: "The plane is taxiing to the runway for takeoff.",
      explanation: "A strip of land where planes take off and land.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Cockpit",
      arabicTranslation: "قمرة القيادة",
      phrase: "The pilot returned to the cockpit after greeting the passengers.",
      explanation: "The area in an aircraft where the pilot controls the plane.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Passenger",
      arabicTranslation: "راكب",
      phrase: "The flight carried 150 passengers.",
      explanation: "A person who is traveling in a vehicle, plane, or ship.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Boarding",
      arabicTranslation: "الصعود",
      phrase: "Boarding for the flight begins at Gate 12.",
      explanation: "The process of entering an aircraft or ship.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Landing",
      arabicTranslation: "الهبوط",
      phrase: "The plane's landing was smooth despite the weather.",
      explanation: "The act of bringing an aircraft down to the ground.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Delay",
      arabicTranslation: "تأخير",
      phrase: "The flight was delayed due to bad weather.",
      explanation: "A period of time by which something is late or postponed.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Luggage",
      arabicTranslation: "أمتعة",
      phrase: "The airline misplaced my luggage during the transfer.",
      explanation: "Suitcases or bags used to carry belongings when traveling.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Cabin",
      arabicTranslation: "مقصورة",
      phrase: "The cabin crew ensured all passengers were comfortable.",
      explanation: "The interior of the aircraft where passengers sit.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Pilot",
      arabicTranslation: "طيار",
      phrase: "The pilot announced the weather conditions during the flight.",
      explanation: "A person who operates the controls of an aircraft.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Flight Attendant",
      arabicTranslation: "مضيف طيران",
      phrase: "The flight attendant served refreshments during the flight.",
      explanation: "A person who ensures the comfort and safety of passengers on an aircraft.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Itinerary",
      arabicTranslation: "برنامج الرحلة",
      phrase: "The travel agency prepared an itinerary for the business trip.",
      explanation: "A planned route or schedule for a journey.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Cargo",
      arabicTranslation: "حمولة",
      phrase: "The cargo plane carried essential goods to the remote area.",
      explanation: "Goods carried on a ship, aircraft, or vehicle.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Customs",
      arabicTranslation: "الجمارك",
      phrase: "We had to declare our purchases at customs.",
      explanation: "The authorities that check goods and travelers entering a country.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Layover",
      arabicTranslation: "محطة توقف",
      phrase: "We had a 3-hour layover in Dubai before the next flight.",
      explanation: "A short stay between two parts of a journey.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Tarmac",
      arabicTranslation: "المدرج",
      phrase: "The passengers waited on the tarmac while the plane refueled.",
      explanation: "The surface of the area where aircraft park or taxi.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Overhead Bin",
      arabicTranslation: "الصندوق العلوي",
      phrase: "Please store your bag in the overhead bin.",
      explanation: "A storage compartment above passengers' seats on an aircraft.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Check-in",
      arabicTranslation: "تسجيل الوصول",
      phrase: "You should arrive early for check-in at the airport.",
      explanation: "The process of confirming a passenger’s presence for a flight.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Runway Incursion",
      arabicTranslation: "اقتحام المدرج",
      phrase: "The pilot reported a runway incursion to air traffic control.",
      explanation: "An unauthorized presence on the runway that could cause a safety hazard.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Altitude Indicator",
      arabicTranslation: "مؤشر الارتفاع",
      phrase: "The altitude indicator showed the plane was at 30,000 feet.",
      explanation: "An instrument that displays the aircraft's height above sea level.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Taxiing",
      arabicTranslation: "السير على المدرج",
      phrase: "The plane is taxiing to the runway for departure.",
      explanation: "The movement of an aircraft on the ground before takeoff or after landing.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Briefing",
      arabicTranslation: "إيجاز",
      phrase: "The pilot gave a briefing before the flight.",
      explanation: "A short meeting or summary of important information.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Business Class",
      arabicTranslation: "درجة رجال الأعمال",
      phrase: "She prefers to travel in business class for added comfort.",
      explanation: "A class of seating and service on an airplane designed for business travelers.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Economy Class",
      arabicTranslation: "الدرجة الاقتصادية",
      phrase: "The majority of passengers choose economy class for affordability.",
      explanation: "The standard class of seating on an airplane.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Fuel Efficiency",
      arabicTranslation: "كفاءة الوقود",
      phrase: "The airline focuses on fuel efficiency to reduce costs.",
      explanation: "The amount of fuel used by an aircraft relative to the distance traveled.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Air Traffic Control",
      arabicTranslation: "مراقبة الحركة الجوية",
      phrase: "Air traffic control ensured a safe landing for the aircraft.",
      explanation: "A service that directs aircraft to ensure safe flight operations.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Trainee",
      arabicTranslation: "متدرب",
      phrase: "The trainee pilot practiced emergency landing techniques.",
      explanation: "A person who is learning and practicing new skills.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Fuselage",
      arabicTranslation: "هيكل الطائرة",
      phrase: "The fuselage was inspected for damage after the flight.",
      explanation: "The central body of an airplane, holding passengers and cargo.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Freight",
      arabicTranslation: "شحن",
      phrase: "The airline specializes in freight services.",
      explanation: "Goods transported in bulk by truck, train, ship, or aircraft.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Decompression",
      arabicTranslation: "إزالة الضغط",
      phrase: "The cabin experienced sudden decompression at high altitude.",
      explanation: "The reduction of pressure in an aircraft cabin.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Pilot in Command",
      arabicTranslation: "قائد الطائرة",
      phrase: "The pilot in command ensured the flight went smoothly.",
      explanation: "The person legally responsible for the operation of the aircraft.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Boarding Pass",
      arabicTranslation: "بطاقة الصعود",
      phrase: "You need a boarding pass to board the plane.",
      explanation: "A document that allows a passenger to enter the restricted area of an airport and board the aircraft.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Jet Lag",
      arabicTranslation: "إجهاد السفر",
      phrase: "She experienced jet lag after a long-haul flight.",
      explanation: "A temporary condition caused by crossing multiple time zones rapidly.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Cockpit",
      arabicTranslation: "قمرة القيادة",
      phrase: "The cockpit contains all the controls for flying the aircraft.",
      explanation: "The area where the pilot and co-pilot sit to operate the plane.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Inflight Entertainment",
      arabicTranslation: "ترفيه على متن الطائرة",
      phrase: "The inflight entertainment included movies and music.",
      explanation: "The entertainment options available to passengers during a flight.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Landing Gear",
      arabicTranslation: "معدات الهبوط",
      phrase: "The landing gear was inspected before takeoff.",
      explanation: "The wheels or other structures that support the aircraft when on the ground.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Flight Plan",
      arabicTranslation: "خطة الطيران",
      phrase: "The pilot submitted the flight plan before departure.",
      explanation: "A detailed schedule of an aircraft’s journey, including routes and destinations.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Airworthiness",
      arabicTranslation: "صلاحية الطيران",
      phrase: "The aircraft was inspected to ensure its airworthiness.",
      explanation: "The condition of being safe to fly.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Turbulence",
      arabicTranslation: "الاضطرابات الهوائية",
      phrase: "The captain warned passengers about upcoming turbulence.",
      explanation: "Irregular air movements that can cause the plane to shake.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Departure Lounge",
      arabicTranslation: "صالة المغادرة",
      phrase: "Passengers waited in the departure lounge for boarding to begin.",
      explanation: "A seating area for passengers waiting to board their flight.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Aircraft Maintenance",
      arabicTranslation: "صيانة الطائرات",
      phrase: "Regular aircraft maintenance ensures safety and reliability.",
      explanation: "The process of servicing and repairing aircraft to keep them in good condition.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Runway",
      arabicTranslation: "مدرج الطائرة",
      phrase: "The plane accelerated down the runway before takeoff.",
      explanation: "A long strip of ground where aircraft take off and land.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Cabin Crew",
      arabicTranslation: "طاقم المقصورة",
      phrase: "The cabin crew ensured all passengers were seated before takeoff.",
      explanation: "The staff responsible for passenger care and safety during the flight.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Emergency Exit",
      arabicTranslation: "مخرج الطوارئ",
      phrase: "Please locate the nearest emergency exit in case of an emergency.",
      explanation: "An exit designed for use during an emergency evacuation.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Black Box",
      arabicTranslation: "الصندوق الأسود",
      phrase: "The black box was recovered to analyze the crash.",
      explanation: "A flight recorder used to record cockpit conversations and flight data.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Final Approach",
      arabicTranslation: "الاقتراب النهائي",
      phrase: "The aircraft was on its final approach to the runway.",
      explanation: "The last part of the flight before landing.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Ground Handling",
      arabicTranslation: "الخدمات الأرضية",
      phrase: "The ground handling team prepared the aircraft for its next flight.",
      explanation: "Services provided to an aircraft while it is on the ground.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Altitude",
      arabicTranslation: "الارتفاع",
      phrase: "The plane reached a cruising altitude of 35,000 feet.",
      explanation: "The height of an object in relation to sea level or ground level.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Standby",
      arabicTranslation: "الانتظار",
      phrase: "The passenger was put on standby for the next available flight.",
      explanation: "A status for travelers waiting for a seat to become available.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Aviation",
      arabicTranslation: "الطيران",
      phrase: "She pursued a career in aviation as a pilot.",
      explanation: "The design, development, and operation of aircraft.",
      createdAt: DateTime.now(),
    ),
    LessonModel(
      englishWord: "Restricted Area",
      arabicTranslation: "منطقة محظورة",
      phrase: "Only authorized personnel are allowed in the restricted area.",
      explanation: "An area in an airport or aircraft accessible only to certain individuals.",
      createdAt: DateTime.now(),
    ),
  ];

  List<LessonModel> getDailyLessons() {
    _lessons.shuffle();
    return _lessons.take(3).toList();
  }
}